apiVersion: operator.openshift.io/v1
kind: DNS
metadata:
  name: default
spec:
  upstreamResolvers:
    policy: Sequential
    upstreams:
    - type: Network
      address: 10.78.214.62
      port: 53
    - type: Network
      address: 103.247.36.36
      port: 53
