apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 99-master-host-network-customizations
spec:
  config:
    ignition:
      version: 3.4.0
    passwd:
      users:
        - name: core
          passwordHash: "$6$jamyHU6tcWovxP.e$rasKzY7tDn.LlazCF6Z4osY86aaXGEFOnkDSClPCw1B/DzPn2knv/kHCwncynti2r3k8MSLwcEsyEwqkDwZd8/"
    storage:
      files:
        - path: /etc/NetworkManager/system-connections/enP13s20f0np0.nmconnection
          overwrite: true
          mode: 384
          contents:
            compression: gzip
            source: data:;base64,H4sICCQjKGoAA2VuUDEzczIwZjBucDAubm1jb25uZWN0aW9uAF2NzQrCMBCE7/suxvzRCpJ38F56WJutBuymJFulb29BkSLMafhmvm7IzDRIytxDioH4Yly1etQ8a5B1pkByp8IkkFiojDjQgXGiPxQXyd+vIGUhgC7NT9/DtO1zDBPygg/AGAvVSjUYrdqTssYrr4+2hRsKvXDd9c5B5D3Y2LPRTlnfKtds+TianyOmitcHRXgDjI/qldYAAAA=
        - path: /etc/NetworkManager/dnsmasq.d/ocp-sno.conf
          overwrite: true
          mode: 420
          contents:
            compression: gzip
            source: data:;base64,H4sICCwjKGoAA29jcC1zbm8uY29uZgCdjc0KAjEMhO99l6Y/u2y97MFHiW3EQKmlrV3w6e1FXBFBzOQ0Mx8Trx7jqjoVlOV24gSpc2CUuVBn2pTAEArVuirMDN97RoM7gDUzzPqNkZzaH1yuv0KRa6Mkn6yxDvSQ+Qj2kEd/IVn5TsPXWlQqY27XWezLm8DODqZlvDhzbFTkcZx4ACrj5Ok9AQAA
        - path: /etc/NetworkManager/conf.d/dnsmasq.conf
          overwrite: true
          mode: 420
          contents:
            source: data:,%5Bmain%5D%0Adns%3Ddnsmasq%0A
        - path: /etc/ssh/sshd_config.d/01-password-auth.conf
          overwrite: true
          mode: 420
          contents:
            source: data:,PasswordAuthentication%20yes%0A
