apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 99-master-container-policy
spec:
  config:
    ignition:
      version: 3.4.0
    storage:
      files:
        - path: /etc/containers/policy.json
          overwrite: true
          mode: 420
          contents:
            source: data:;base64,ewogICAgICAiZGVmYXVsdCI6IFsKICAgICAgICB7CiAgICAgICAgICAidHlwZSI6ICJpbnNlY3VyZUFjY2VwdEFueXRoaW5nIgogICAgICAgIH0KICAgICAgXSwKICAgICAgInRyYW5zcG9ydHMiOiB7CiAgICAgICAgImRvY2tlci1kYWVtb24iOiB7CiAgICAgICAgICAiIjogW3sidHlwZSI6ICJpbnNlY3VyZUFjY2VwdEFueXRoaW5nIn1dCiAgICAgICAgfQogICAgICB9Cn0K
