apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 99-master-zz-unsigned-policy
spec:
  config:
    ignition:
      version: 3.4.0
    storage:
      files:
        - path: /etc/containers/policy.json
          mode: 420
          overwrite: true
          contents:
            compression: gzip
            source: data:;base64,H4sIAKFBf2oAA6tWUOBSAAGllNS0xNKcEiUrhehqpZLKglQgSykzrzg1ubQo1TE5ObWgxDGvsiQjMy9dqTZWB6qrpCgxr7ggv6ikGKi8GiIIFE4syc/NTAYJKRFpYK0OXHNKfnJ2ahFFmnVTElNz8/NIMgMWErVcYAIAiEOd/BoBAAA=
